export const themes = [
  {
    id: 'amber',
    name: 'Amber',
    swatch: '#b45309',
    vars: {
      '--t-page':         '#fffbeb',
      '--t-hdr':          '#78350f',
      '--t-hdr-text':     '#fefce8',
      '--t-hdr-sub':      '#fcd34d',
      '--t-btn':          '#b45309',
      '--t-btn-hover':    '#92400e',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#fef3c7',
      '--t-btn2-hover':   '#fde68a',
      '--t-btn2-text':    '#78350f',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#fef3c7',
      '--t-accent':       '#b45309',
      '--t-ring':         '#fbbf24',
      '--t-banner-bg':    '#fef3c7',
      '--t-banner-border':'#fcd34d',
      '--t-banner-text':  '#78350f',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    swatch: '#15803d',
    vars: {
      '--t-page':         '#f0fdf4',
      '--t-hdr':          '#14532d',
      '--t-hdr-text':     '#f0fdf4',
      '--t-hdr-sub':      '#86efac',
      '--t-btn':          '#15803d',
      '--t-btn-hover':    '#166534',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#dcfce7',
      '--t-btn2-hover':   '#bbf7d0',
      '--t-btn2-text':    '#14532d',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#dcfce7',
      '--t-accent':       '#15803d',
      '--t-ring':         '#4ade80',
      '--t-banner-bg':    '#dcfce7',
      '--t-banner-border':'#86efac',
      '--t-banner-text':  '#14532d',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    swatch: '#1d4ed8',
    vars: {
      '--t-page':         '#eff6ff',
      '--t-hdr':          '#1e3a8a',
      '--t-hdr-text':     '#eff6ff',
      '--t-hdr-sub':      '#93c5fd',
      '--t-btn':          '#1d4ed8',
      '--t-btn-hover':    '#1e40af',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#dbeafe',
      '--t-btn2-hover':   '#bfdbfe',
      '--t-btn2-text':    '#1e3a8a',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#dbeafe',
      '--t-accent':       '#1d4ed8',
      '--t-ring':         '#60a5fa',
      '--t-banner-bg':    '#dbeafe',
      '--t-banner-border':'#93c5fd',
      '--t-banner-text':  '#1e3a8a',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    swatch: '#4338ca',
    vars: {
      '--t-page':         '#eef2ff',
      '--t-hdr':          '#0f172a',
      '--t-hdr-text':     '#f8fafc',
      '--t-hdr-sub':      '#64748b',
      '--t-btn':          '#4338ca',
      '--t-btn-hover':    '#3730a3',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#e0e7ff',
      '--t-btn2-hover':   '#c7d2fe',
      '--t-btn2-text':    '#1e1b4b',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#e0e7ff',
      '--t-accent':       '#4338ca',
      '--t-ring':         '#818cf8',
      '--t-banner-bg':    '#e0e7ff',
      '--t-banner-border':'#a5b4fc',
      '--t-banner-text':  '#1e1b4b',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    swatch: '#be123c',
    vars: {
      '--t-page':         '#fff1f2',
      '--t-hdr':          '#881337',
      '--t-hdr-text':     '#fff1f2',
      '--t-hdr-sub':      '#fda4af',
      '--t-btn':          '#be123c',
      '--t-btn-hover':    '#9f1239',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#ffe4e6',
      '--t-btn2-hover':   '#fecdd3',
      '--t-btn2-text':    '#881337',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#ffe4e6',
      '--t-accent':       '#be123c',
      '--t-ring':         '#fb7185',
      '--t-banner-bg':    '#ffe4e6',
      '--t-banner-border':'#fda4af',
      '--t-banner-text':  '#881337',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    swatch: '#475569',
    vars: {
      '--t-page':         '#f8fafc',
      '--t-hdr':          '#1e293b',
      '--t-hdr-text':     '#f8fafc',
      '--t-hdr-sub':      '#94a3b8',
      '--t-btn':          '#475569',
      '--t-btn-hover':    '#334155',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#f1f5f9',
      '--t-btn2-hover':   '#e2e8f0',
      '--t-btn2-text':    '#1e293b',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#e2e8f0',
      '--t-accent':       '#475569',
      '--t-ring':         '#94a3b8',
      '--t-banner-bg':    '#f1f5f9',
      '--t-banner-border':'#e2e8f0',
      '--t-banner-text':  '#1e293b',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    swatch: '#ea580c',
    vars: {
      '--t-page':         '#fff7ed',
      '--t-hdr':          '#7c2d12',
      '--t-hdr-text':     '#fff7ed',
      '--t-hdr-sub':      '#fdba74',
      '--t-btn':          '#ea580c',
      '--t-btn-hover':    '#c2410c',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#ffedd5',
      '--t-btn2-hover':   '#fed7aa',
      '--t-btn2-text':    '#7c2d12',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#ffedd5',
      '--t-accent':       '#ea580c',
      '--t-ring':         '#fb923c',
      '--t-banner-bg':    '#ffedd5',
      '--t-banner-border':'#fdba74',
      '--t-banner-text':  '#7c2d12',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    swatch: '#7c3aed',
    vars: {
      '--t-page':         '#faf5ff',
      '--t-hdr':          '#4a1d96',
      '--t-hdr-text':     '#faf5ff',
      '--t-hdr-sub':      '#c4b5fd',
      '--t-btn':          '#7c3aed',
      '--t-btn-hover':    '#6d28d9',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#ede9fe',
      '--t-btn2-hover':   '#ddd6fe',
      '--t-btn2-text':    '#4a1d96',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#ede9fe',
      '--t-accent':       '#7c3aed',
      '--t-ring':         '#a78bfa',
      '--t-banner-bg':    '#ede9fe',
      '--t-banner-border':'#c4b5fd',
      '--t-banner-text':  '#4a1d96',
    },
  },
  {
    id: 'crimson',
    name: 'Crimson',
    swatch: '#b91c1c',
    vars: {
      '--t-page':         '#fef2f2',
      '--t-hdr':          '#7f1d1d',
      '--t-hdr-text':     '#fef2f2',
      '--t-hdr-sub':      '#fca5a5',
      '--t-btn':          '#b91c1c',
      '--t-btn-hover':    '#991b1b',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#fee2e2',
      '--t-btn2-hover':   '#fecaca',
      '--t-btn2-text':    '#7f1d1d',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#fee2e2',
      '--t-accent':       '#b91c1c',
      '--t-ring':         '#f87171',
      '--t-banner-bg':    '#fee2e2',
      '--t-banner-border':'#fca5a5',
      '--t-banner-text':  '#7f1d1d',
    },
  },
  {
    id: 'sage',
    name: 'Sage',
    swatch: '#4d7c0f',
    vars: {
      '--t-page':         '#f7fee7',
      '--t-hdr':          '#365314',
      '--t-hdr-text':     '#f7fee7',
      '--t-hdr-sub':      '#a3e635',
      '--t-btn':          '#4d7c0f',
      '--t-btn-hover':    '#3f6212',
      '--t-btn-text':     '#ffffff',
      '--t-btn2':         '#ecfccb',
      '--t-btn2-hover':   '#d9f99d',
      '--t-btn2-text':    '#365314',
      '--t-card':         '#ffffff',
      '--t-card-border':  '#ecfccb',
      '--t-accent':       '#4d7c0f',
      '--t-ring':         '#84cc16',
      '--t-banner-bg':    '#ecfccb',
      '--t-banner-border':'#a3e635',
      '--t-banner-text':  '#365314',
    },
  },
]

export const defaultTheme = themes[0]
